apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/helloworld

patches:
  - path: configmap.yaml
  - path: secrets.yaml
  - target:
      kind: Ingress
      name: helloworld
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: helloworld-dev.training.jambit.space
      - op: replace
        path: /spec/tls/0/hosts/0
        value: helloworld-dev.training.jambit.space