apiVersion: v1
kind: Secret
metadata:
    name: helloworld-secret
type: Opaque
stringData:
    SECRETNAME: ENC[AES256_GCM,data:2xAIOj9BUOzKHNNs46g=,iv:qaPgK40xCIXYKIy05JM28V8RoSYTs821AVuMcyz888Y=,tag:lViesPoMW36LCYBusMKvNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVVlRMzZFQUlBbWp6SWtO
            YzhHYzd4SEJlNHdGYW81ZUlYUkNHQnd2bGdZCk5iQ0VDSHkydElnWlRTeFhlcGNW
            MU1QdmtXNDlwYzJpWXV3UmVDbTRoRjgKLS0tIHBxM0ZXYXJKRFBIRWVDb0gxVG5O
            MTdmMU5heXpYTlI1bzZiWWxBVVVDWW8Kzjv9omTbs+uKzEnRgvG4QN9Ancvf8PhV
            m+kWhgbjNwDcZl+3jd9mBiN8R1EsXdXd9TQxLR98stuGuatSm9WK8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19kyyjnd32na99sn2d4ktqddykrmnghu6tk34fsy9l9duyu2g95ssypk7vy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T13:54:03Z"
    mac: ENC[AES256_GCM,data:2j+eAGTMd2dlAjqoHqp0C6ZhjV/x0XP3n1g4oNE+8SN0Ud65rglWa536QTvX7Fyi8ThuTHIym9RZvyWJ31V/kRI4xhgLiFhz2k0ONr9xKjMxkCFRFHFVkcLFVFOKxo2IU/I7WnBvq7cNyE2/L7+Mxk2SyqU8dASFG1hA1LhoeZI=,iv:2FOCBdA4EC4dUhuPNgfk8WdDL0F1HyFx2zQWWhG0zlQ=,tag:CnwleIUFrVrLqdy7FJY5bQ==,type:str]
    version: 3.13.2
